### PR TITLE
Improve performance by caching Filament components and warn if APP_KEY is missing

### PR DESCRIPTION
**Pull request by alexjustesen**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-speedtest-tracker/blob/main/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

This PR improves performance by caching Filament components during startup and will now warn a user if an `APP_KEY` is not present and how to generate one.

## Benefits of this PR and context:

Improving performance by caching views and documentation by guiding user setup.

## How Has This Been Tested?

Same startup process for caching I'm using in `app:install` command for development.

## Source / References:

https://github.com/alexjustesen/speedtest-tracker/blob/ce697bd9aae51227130ef97d2ec80647a3a6e134/app/Console/Commands/InstallCommand.php#L41-L43

### CODE REVIEW

**Comment by thespad** [comment]
If we're going to make that change then you also need to update the readme-vars to move the APP_KEY env from optional to mandatory and add a note to the changelog so we've got an easy record of when the change was made.

**Comment by alexjustesen** [comment]
On it

**Comment by thespad** [comment]
Just the readme-vars, the actual readme.md is templated at build time.

**Comment by alexjustesen** [comment]
@thespad pushed the updates, let me know if you need anything else

**Comment by thespad** [comment]
So based on my testing of 0.20, `DISPLAY_TIMEZONE` now seems to be mandatory too (not sure if that's intentional or not, but I'm getting
```
[2024-06-07 12:48:03] production.ERROR: Carbon\Carbon::timezone(): Argument #1 ($value) must be of type DateTimeZone|string|int, null given, called in /app/www/app/Filament/Widgets/RecentUploadLatencyChartWidget.php on line 83 {"userId":1,"exception":"[object] (TypeError(code: 0): Carbon\\Carbon::timezone(): Argument #1 ($value) must be of type DateTimeZone|string|int, null given, called in /app/www/app/Filament/Widgets/RecentUploadLatencyChartWidget.php on line 83 at /app/www/vendor/nesbot/carbon/src/Carbon/Traits/Date.php:1831)
```
Without it set. We can set it to a UTC default in the Dockerfiles if that's easier.

Also your example settings for `SPEEDTEST_SCHEDULE` and `SPEEDTEST_SERVERS` should either be
```yaml
      - SPEEDTEST_SCHEDULE=47 */6 * * *
      - SPEEDTEST_SERVERS=60700,51643,57802,22971
```
or
```yaml
      - "SPEEDTEST_SCHEDULE=47 */6 * * *"
      - "SPEEDTEST_SERVERS=60700,51643,57802,22971"
```
or even
```yaml
      SPEEDTEST_SCHEDULE: 47 */6 * * *
      SPEEDTEST_SERVERS: 60700,51643,57802,22971
```
but not
```yaml
      - SPEEDTEST_SCHEDULE="47 */6 * * *"
      - SPEEDTEST_SERVERS="60700,51643,57802,22971"
```
As that will include the quotes as part of the env (unless you have code in place to handle that internally).

**Comment by thespad** [comment]
Oh, also you might want to change `Get a key at` to `You can generate a key at` so that people don't read it as implying some kind of license key situation.

**Comment by alexjustesen** [comment]
> Oh, also you might want to change `Get a key at` to `You can generate a key at` so that people don't read it as implying some kind of license key situation.

Good catch, it does sound like one is required.

I should be defaulting to `UTC` in the application instead of `null` so this PR https://github.com/alexjustesen/speedtest-tracker/pull/1471 fixes that and will be in `v0.20.1` that I'll release in a few.

Also examples have been updated, thanks for the suggestion. I wrote them looking at my `.env` file locally.

**Comment by thespad** [comment]
Seeing `cp: cannot stat '/app/www/.env.production': No such file or directory` in the startup, is that file no longer there?

Should we be copying env.example instead?

**Comment by alexjustesen** [comment]
> Seeing `cp: cannot stat '/app/www/.env.production': No such file or directory` in the startup, is that file no longer there?
> 
> Should we be copying env.example instead?
> 
> Edit: here https://github.com/linuxserver/docker-speedtest-tracker/blob/main/root/etc/s6-overlay/s6-rc.d/init-speedtest-tracker-config/run#L65-L68

I'm no longer using `.env` in the file system for environment variables and instead want people to set those in their Docker Docker Compose files.

I can remove this copy statement in a few unless I'm missing an issue this would cause. I do believe I have coverage across vars with `APP_KEY` being required.

**Comment by thespad** [comment]
You need to also change this `if` block
```bash
if ! grep -E "APP_KEY=[0-9A-Za-z:+\/=]{1,}" /app/www/.env > /dev/null; then
```
Probably to something like
```bash
if ! grep -qE "APP_KEY=[0-9A-Za-z:+\/=]{1,}" /app/www/.env 2> /dev/null; then
```
So that it will handle people who already have an APP_KEY set in their .env file but won't error if there isn't one at all.

**Comment by alexjustesen** [comment]
I also moved creating the symlink to only if an `.env` file exists, thinking this might make better sense for backwards compatibility.

**Comment by thespad** [comment]
I think we need to do a `sleep infinity` if no APP_KEY is found otherwise it'll appear to start OK but just 500 error and not be clear why unless users dig into the logs.

**Comment by thespad** [comment]
Realised it was quicker just to do those bits myself - added an app_key to the CI envs so it boots correctly for the CI tests.

**Comment by alexjustesen** [comment]
Cool thank you, I've been trying to respond between meetings this morning.

**Comment by thespad** [comment]
Oh, I forgot to ask, what's the behaviour for an existing user updating to 0.20 who *doesn't* set SPEEDTEST_SCHEDULE or SPEEDTEST_SERVERS?

**Comment by alexjustesen** [comment]
Their scheduled tests will stop until they get those options setup.

**Comment by thespad** [comment]
In that case I'd suggest some kind of UI indication that there's no schedule and/or server selection or we're going to get a bunch of users who don't understand why their installs have stopped working.

**Comment by thespad** [comment]
Oh and don't worry about the CI tests failing all of a sudden, I forgot that external PRs don't use the generated Jenkinsfile for security reasons, so the sleep is taking effect and not the APP_KEY env, but it'll be fine once merged.

**Comment by alexjustesen** [comment]
> In that case I'd suggest some kind of UI indication that there's no schedule and/or server selection or we're going to get a bunch of users who don't understand why their installs have stopped working.

Good idea, captured that separately so I don't lose it in comments.

https://github.com/alexjustesen/speedtest-tracker/issues/1475

**Comment by thespad** [comment]
Updated the readme with the new envs, I think we're probably good to merge this unless you've got anything else you think needs to be updated?

**Review by aptalca — APPROVED** [review]

**Comment by alexjustesen** [comment]
> Updated the readme with the new envs, I think we're probably good to merge this unless you've got anything else you think needs to be updated?

I'm good, any issues should be application side which I'll handle in app releases. Thanks!

**Pull request merged**
